const countryList = {
  AED: "United Arab Emirates",
  AFN: "Afghanistan",
  XCD: "Antigua and Barbuda",
  ALL: "Albania",
  AMD: "Armenia",
  ANG: "Netherlands Antilles",
  AOA: "Angola",
  AQD: "Antarctica",
  ARS: "Argentina",
  AUD: "Australia",
  AZN: "Azerbaijan",
  BAM: "Bosnia and Herzegovina",
  BBD: "Barbados",
  BDT: "Bangladesh",
  XOF: "Belgium",
  BGN: "Bulgaria",
  BHD: "Bahrain",
  BIF: "Burundi",
  BMD: "Bermuda",
  BND: "Brunei Darussalam",
  BOB: "Bolivia",
  BRL: "Brazil",
  BSD: "Bahamas",
  NOK: "Bouvet Island",
  BWP: "Botswana",
  BYR: "Belarus",
  BZD: "Belize",
  CAD: "Canada",
  CDF: "Congo, Democratic Republic of the",
  XAF: "Central African Republic",
  CHF: "Switzerland",
  CLP: "Chile",
  CNY: "China",
  COP: "Colombia",
  CRC: "Costa Rica",
  CUP: "Cuba",
  CVE: "Cape Verde",
  CYP: "Cyprus",
  CZK: "Czech Republic",
  DJF: "Djibouti",
  DKK: "Denmark",
  DOP: "Dominican Republic",
  DZD: "Algeria",
  ECS: "Ecuador",
  EEK: "Estonia",
  EGP: "Egypt",
  ETB: "Ethiopia",
  EUR: "France",
  FJD: "Fiji",
  FKP: "Falkland Islands (Malvinas)",
  GBP: "United Kingdom",
  GEL: "Georgia",
  GGP: "Guernsey",
  GHS: "Ghana",
  GIP: "Gibraltar",
  GMD: "Gambia",
  GNF: "Guinea",
  GTQ: "Guatemala",
  GYD: "Guyana",
  HKD: "Hong Kong",
  HNL: "Honduras",
  HRK: "Croatia",
  HTG: "Haiti",
  HUF: "Hungary",
  IDR: "Indonesia",
  ILS: "Israel",
  INR: "India",
  IQD: "Iraq",
  IRR: "Iran, Islamic Republic of",
  ISK: "Iceland",
  JMD: "Jamaica",
  JOD: "Jordan",
  JPY: "Japan",
  KES: "Kenya",
  KGS: "Kyrgyzstan",
  KHR: "Cambodia",
  KMF: "Comoros",
  KPW: "Korea, Democratic People's Republic of",
  KRW: "Korea, Republic of",
  KWD: "Kuwait",
  KYD: "Cayman Islands",
  KZT: "Kazakhstan",
  LAK: "Lao People's Democratic Republic",
  LBP: "Lebanon",
  LKR: "Sri Lanka",
  LRD: "Liberia",
  LSL: "Lesotho",
  LTL: "Lithuania",
  LVL: "Latvia",
  LYD: "Libyan Arab Jamahiriya",
  MAD: "Morocco",
  MDL: "Moldova, Republic of",
  MGA: "Madagascar",
  MKD: "Macedonia, the Former Yugoslav Republic of",
  MMK: "Myanmar",
  MNT: "Mongolia",
  MOP: "Macao",
  MRO: "Mauritania",
  MTL: "Malta",
  MUR: "Mauritius",
  MVR: "Maldives",
  MWK: "Malawi",
  MXN: "Mexico",
  MYR: "Malaysia",
  MZN: "Mozambique",
  NAD: "Namibia",
  XPF: "New Caledonia",
  NGN: "Nigeria",
  NIO: "Nicaragua",
  NPR: "Nepal",
  NZD: "New Zealand",
  OMR: "Oman",
  PAB: "Panama",
  PEN: "Peru",
  PGK: "Papua New Guinea",
  PHP: "Philippines",
  PKR: "Pakistan",
  PLN: "Poland",
  PYG: "Paraguay",
  QAR: "Qatar",
  RON: "Romania",
  RSD: "Serbia",
  RUB: "Russian Federation",
  RWF: "Rwanda",
  SAR: "Saudi Arabia",
  SBD: "Solomon Islands",
  SCR: "Seychelles",
  SDG: "Sudan",
  SEK: "Sweden",
  SGD: "Singapore",
  SKK: "Slovakia",
  SLL: "Sierra Leone",
  SOS: "Somalia",
  SRD: "Suriname",
  STD: "Sao Tome and Principe",
  SVC: "El Salvador",
  SYP: "Syrian Arab Republic",
  SZL: "Swaziland",
  THB: "Thailand",
  TJS: "Tajikistan",
  TMT: "Turkmenistan",
  TND: "Tunisia",
  TOP: "Tonga",
  TRY: "Turkey",
  TTD: "Trinidad and Tobago",
  TWD: "Taiwan, Province of China",
  TZS: "Tanzania, United Republic of",
  UAH: "Ukraine",
  UGX: "Uganda",
  USD: "United States",
  UYU: "Uruguay",
  UZS: "Uzbekistan",
  VEF: "Venezuela",
  VND: "Viet Nam",
  VUV: "Vanuatu",
  YER: "Yemen",
  ZAR: "South Africa",
  ZMK: "Zambia",
  ZWD: "Zimbabwe",
};
